/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:8799981d-d457-41c2-811b-f83475e90329",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_B6mngRXAN",
    "aws_user_pools_web_client_id": "6nt3nv556d6ko5m75iofehvhpb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xitaad46nbhqzojvdkegx5fo54.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
